# -*- mode: python ; coding: utf-8 -*-
# Run from repo root:
#   python -m PyInstaller --noconfirm --distpath dist --workpath dist/pyinstaller-work scripts/packaging/yizhi-backend.spec

block_cipher = None

hiddenimports = [
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "fastapi",
    "starlette",
    "anyio",
    "anyio._backends._asyncio",
    "pydantic",
    "yaml",
    "multipart",
    "backend",
    "backend.server",
    "backend.__frozen_main__",
    "lib",
]

a = Analysis(
    ["../../backend/__frozen_main__.py"],
    pathex=["../.."],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "pytest",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "IPython",
        "jupyter",
        "notebook",
        "nbformat",
        "nbclient",
        "jedi",
        "zmq",
        "pygments",
        "torch",
        "torchvision",
        "torchaudio",
        "tensorflow",
        "tensorboard",
        "onnxruntime",
        "scipy",
        "sympy",
        "sklearn",
        "cv2",
        "lazyllm",
        "sphinx",
        "docutils",
        "babel",
        "imageio",
        "imageio_ffmpeg",
        "PIL.ImageQt",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="yizhi-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="yizhi-backend",
)
